Fix package.json to allow Next 15 and React 19
shuding/next-view-transitions pull request #50
Opened 2024-12-12 14:01 UTC by XusBadia

The recent change to update for Next 15 didn't account for React 19, so I updated the package.json.

2024-12-17 20:49 UTC, dani-z approved these changes

2024-12-17 20:52 UTC, dani-z requested changes

2024-12-17 20:52 UTC, dani-z commented on package.json
> +  }
Missing comma

2024-12-23 12:39 UTC, KrenTrox approved these changes

2024-12-31 01:43 UTC, merged